apiVersion: v1
kind: Secret
metadata:
  name:  express-env
type: Opaque
data:
   DATABASE_URL: bXlzcWw6Ly9mb3J0aHJlZTpmb3J0cmVlQDM0LjQ0LjgwLjEzMDozMzA2L3Rlc3Q=
   SECRET_KEY: UExqUzFxcUlpUXNETGpZZFdBWURFRFhRTzFQUzZsMVFJNWFwUExUUWZQNlhxV2JLRUwwU2hlV2FLOTdobjRZNTBXOWVLU0ZFekNGcE9SZHJtM0VTb0E=